# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

permissions:
    contents: read

jobs:
    python-e2e:
        
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Run E2E tests for Pyhton
              run: |
                  cd python
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                  python -m uvicorn main:app --reload &
                  while ! nc -z localhost 8000; do sleep 1; done &
                  echo "API is up" &
                  echo "===========================" &
                  cd ..
                  dotnet test LastSeenDemo.E2E.ForPython
